ifeq ($(OS),Windows_NT) 
RM = del
FS = \\
EXTENSION = exe
else
RM = rm
FS = /
EXTENSION = out
endif

CC = gcc	
TARGET = program
FLAGS = -g -Wall -v -pedantic

FILENAME = main
CLUSTER_MODULE = ClusterModule${FS}Cluster
ASYM_MODULE_PATH = ConvertGraph${FS}AsymGraphToSym
CSV_TO_LIST_MODULE = CSVModule${FS}CSVtoDoubleList${FS}CSVToList
LAT_LON_MODULE = CSVModule${FS}ReadLatLon${FS}readLatLon
CSV_MODULE_PATH = CSVModule${FS}CSVtoMatrix
LIST_TO_CSV_MODULE = CSVModule${FS}matrixToCSV
FILTER_MODULE = FilterModule${FS}MatrixFilter
LINKED_LISTS = LinkedLists${FS}List
MATRIX_MODULE_PATH = MatrixModule${FS}MatrixOperations
TSP_MODULE_PATH = TSP${FS}tspModule
SIM_MODULE_PATH = Simulation${FS}SimModule
WASTE_MANAGEMENT = WasteManagement${FS}WasteManagement
TRADITIONALROUTES = TraditionalRoutes${FS}TraditionalRoutes

$(TARGET).exe: $(FILENAME).c $(CSV_MODULE_PATH).o $(MATRIX_MODULE_PATH).o $(ASYM_MODULE_PATH).o $(LAT_LON_MODULE).o $(FILTER_MODULE).o $(CSV_TO_LIST_MODULE).o $(LINKED_LISTS).o $(TSP_MODULE_PATH).o $(CLUSTER_MODULE).o $(LIST_TO_CSV_MODULE).o $(SIM_MODULE_PATH).o $(TRADITIONALROUTES).o $(WASTE_MANAGEMENT).o
	$(CC)  $(FLAGS) $(FILENAME).c $(CSV_MODULE_PATH).o $(MATRIX_MODULE_PATH).o $(ASYM_MODULE_PATH).o $(LAT_LON_MODULE).o $(FILTER_MODULE).o $(CSV_TO_LIST_MODULE).o $(LINKED_LISTS).o $(TSP_MODULE_PATH).o $(CLUSTER_MODULE).o $(LIST_TO_CSV_MODULE).o $(SIM_MODULE_PATH).o $(TRADITIONALROUTES).o $(WASTE_MANAGEMENT).o -o $(TARGET).exe

$(ASYM_MODULE_PATH).o: $(ASYM_MODULE_PATH).c $(ASYM_MODULE_PATH).h
	$(CC) $(FLAGS) -c $(ASYM_MODULE_PATH).c -o $(ASYM_MODULE_PATH).o

$(LAT_LON_MODULE).o: $(LAT_LON_MODULE).c $(LAT_LON_MODULE).h
	$(CC)  $(FLAGS) -c $(LAT_LON_MODULE).c -o $(LAT_LON_MODULE).o

$(CSV_MODULE_PATH).o: $(CSV_MODULE_PATH).c $(CSV_MODULE_PATH).h
	$(CC) $(FLAGS) -c $(CSV_MODULE_PATH).c -o $(CSV_MODULE_PATH).o

$(MATRIX_MODULE_PATH).o: $(MATRIX_MODULE_PATH).c $(MATRIX_MODULE_PATH).h
	$(CC)  $(FLAGS) -c $(MATRIX_MODULE_PATH).c -o $(MATRIX_MODULE_PATH).o

$(LINKED_LISTS).o: $(LINKED_LISTS).c $(LINKED_LISTS).h
	$(CC) $(FLAGS) -c $(LINKED_LISTS).c -o $(LINKED_LISTS).o

$(CLUSTER_MODULE).o : $(CLUSTER_MODULE).c $(CLUSTER_MODULE).h 
	$(CC) $(FLAGS)  -c $(CLUSTER_MODULE).c -o $(CLUSTER_MODULE).o

$(FILTER_MODULE).o : $(FILTER_MODULE).c $(FILTER_MODULE).h
	$(CC) $(FLAGS) -c $(FILTER_MODULE).c -o $(FILTER_MODULE).o

$(CSV_TO_LIST_MODULE).o : $(CSV_TO_LIST_MODULE).c $(CSV_TO_LIST_MODULE).h
	$(CC) $(FLAGS) -c $(CSV_TO_LIST_MODULE).c -o $(CSV_TO_LIST_MODULE).o

$(TSP_MODULE_PATH).o : $(TSP_MODULE_PATH).c $(TSP_MODULE_PATH).h
	$(CC) $(FLAGS) -c $(TSP_MODULE_PATH).c -o $(TSP_MODULE_PATH).o

$(DEPTHFIRST_PATH).o : $(DEPTHFIRST_PATH).c $(DEPTHFIRST_PATH).h
	$(CC) $(FLAGS) -c $(DEPTHFIRST_PATH).c -o $(DEPTHFIRST_PATH).o

$(LIST_TO_CSV_MODULE).o : $(LIST_TO_CSV_MODULE).c $(LIST_TO_CSV_MODULE).h
	$(CC) $(FLAGS) -c $(LIST_TO_CSV_MODULE).c -o $(LIST_TO_CSV_MODULE).o

$(SIM_MODULE_PATH).o : $(SIM_MODULE_PATH).c $(SIM_MODULE_PATH).h
	$(CC) $(FLAGS) -c $(SIM_MODULE_PATH).c -o $(SIM_MODULE_PATH).o

$(WASTE_MANAGEMENT).o : $(WASTE_MANAGEMENT).c $(WASTE_MANAGEMENT).h
	$(CC) $(FLAGS) -c $(WASTE_MANAGEMENT).c -o $(WASTE_MANAGEMENT).o

$(TRADITIONALROUTES).o : $(TRADITIONALROUTES).c $(TRADITIONALROUTES).h
	$(CC) $(FLAGS) -c $(TRADITIONALROUTES).c -o $(TRADITIONALROUTES).o

clean:
	${RM} $(CSV_MODULE_PATH).o $(MATRIX_MODULE_PATH).o $(ASYM_MODULE_PATH).o $(TARGET).${EXTENSION} $(CLUSTER_MODULE).o $(FILTER_MODULE).o \
		$(CSV_TO_LIST_MODULE).o $(LAT_LON_MODULE).o $(TSP_MODULE_PATH).o $(LINKED_LISTS).o $(LIST_TO_CSV_MODULE).o $(SIM_MODULE_PATH).o \
		$(WASTE_MANAGEMENT).o $(TRADITIONALROUTES).o
